nombre: "Godot APK Build"

en:
  empujar:
    sucursales:
      - principal
  flujo_de_trabajo:

empleos:
  exportar-android:
    nombre: Exportar APK de Android
    runs-on: ubuntu-latest
    pasos:
      - nombre: Repositorio de Checkout
        Usos: acciones/checkout@v4

      - nombre: Exportación de Godot
        Usos: firebelley/godot-export@v5.2.1
        con:
          godot_version: 4.2.1
          export_debug: true
          ruta_del_proyecto_relativa: ./

      - nombre: Cargar artefacto APK
        Usos: acciones/cargar-artefacto@v4
        con:
          nombre: Carrera-3D-APK
          ruta: build/android/